name: Nightly Lyre rebuild

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lyre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unshallow repo tags
        run: git fetch --prune --unshallow --tags

      - name: Check if build is necessary
        run: test "$(git tag --points-at HEAD)" = ""

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install make curl git mercurial libarchive-tools xorriso -y

      #- name: Build distro
      #  run: make distro-full

      #- name: Build ISO
      #  run: make all

      #- name: Rename lyre.iso
      #  run: mv lyre.iso lyre-nightly-full-$(date +'%Y%m%d').iso

      #- name: Distclean
      #  run: make distclean

      - name: Build base distro
        run: make distro-base

      - name: Build ISO
        run: make all

      - name: Rename lyre.iso
        run: mv lyre.iso lyre-nightly-base-$(date +'%Y%m%d').iso

      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Tag new nightly release
        run: git tag nightly-$TAG_DATE && git push --tags

      - name: Create nightly release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly build ${{ env.TAG_DATE }}
          tag_name: nightly-${{ env.TAG_DATE }}
          body: Image of an up to date Lyre nightly build.
          files: |
            lyre-nightly-*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
